name: Java CI with Gradle

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Check Gradle version
        run: ./gradlew --version
      - name: Run Gradle build
        run: .\gradlew test --info -Dselenide.headless=true
      - name: Start SUT
        run: java -jar ./artifacts/app-mbank.jar &
      - name: Wait for SUT to start
        run: |
          while ! nc -z localhost 8080; do   
            sleep 1
          done
      - name: Build with Gradle
        run: ./gradlew test --info -Dselenide.headless=true
